### PR TITLE
Fixes `stress.py` in master, regardless of # --nprocess specified

### LINKED ISSUE #161: Resolve `stress.py` errors to confirm SQLite use is fixed
CC @skinner 

Followup work to #156. It appears SQLite use now works as expected on the server-side. No locking and the profiling of DB use shows all queries succeeding -- no errors. 

Yet `stress.py` still has issues. The work here is to sort out what is going on with the test. Hopefully this is  mostly a fix on the test ENV or in the test itself.

The setup here is to have one terminal with the server running.

```
# activate the virtualenv
source ENV/bin/activate

# clear out old DB data
rm -fr smrt-server-analysis/db

# run the server
make start-smrt-server-analysis > debug_db.txt
```

And one running the stress test.
```
# activate the virtualenv
source ENV/bin/activate

# setup needed data
make dataclean
make test-data/smrtserver-testdata

# run the stress test
(ENV)$ ./stress.py 2> stress.err > stress.out
```

Here are example logs of the issues I'm seeing.

[stress_err.txt](https://github.com/PacificBiosciences/smrtflow/files/314583/stress_err.txt)
[stress_out.txt](https://github.com/PacificBiosciences/smrtflow/files/314584/stress_out.txt)

### PR DESCRIPTION
**Pull request by jfalkner**
CC @mpkocher @skinner 

Fixes #161

This PR should be the last set of changes to make `master` pass the existing `stress.py` integration test using SQLite, without the limitation of the `--nprocesses 1` setting. Previous DB refactoring #146 #170 #195

>NOTE! This PR only fixes current `stress.py` testing. I bet we have a few other cases where nested queries are being used and we need to do similar fixes. Those can be fixed in subsequent PRs.

The main fix here is un-nesting `db.run()` use so that one query won't block on another. It seems we simply can't use this practice reliably as long as we're using SQLite and limited to one connection.

GOOD: It'll work
- `DBIO.seq` and `DBIO.sequential` these are both fine as long as the list of statements doesn't invoke new `db.run()`
- `transactionally` is fine to use 

BAD: It'll break
- Don't ever have a `db.run()` `DBIOAction` that relies on a nested `db.run()` invocation
  - e.g. No way to have multiple connections with transactions -- only one transaction may be going at a time. If a parent query uses `.transactionally` it starts a transaction on the only `Connection` and the nested query's transaction will hopelessly block and timeout.
  - e.g. No way to reliably nest `db.run()` even if the nested queries are read-only. You must run the nested queries first then the one that uses the values. If you compose them all together, then there is a race condition where the parent query may block on a nested query that'll never execute due to the single DB connection that runs queries in serial.

See #195 for a [README.md](https://github.com/PacificBiosciences/smrtflow/tree/master/smrt-server-database#detecting-nested-queries-and-sqlite) link and some more details on how to debug cases that'll break.

## Testing

Running the test (normal `sbt test` passes too).
```
# launch the server
$ rm -fr smrt-server-analysis/db
$ make start-smrt-server-analysis > server_out.txt 2> server_err.txt

# run stress.py (in a different term)
./stress.py 2> stress_err.txt > stress_out.txt
```

And see that `stress_out.txt` succeeds. Would be nice to have a more obvious final `PASSED` status.

```
# Look for final summary of stress.py work.
$ cat stress_ou.txt
...
Dataset Summary
----------
SubreadSets 5
HdfSubreadSets 0
ReferenceSets 6
AlignmentSets 0
----------
All Job types Summary
----------
import-dataset Jobs 11
State SUCCESSFUL 11
----------
merge-datasets Jobs 0
----------
convert-fasta-reference Jobs 0
----------
pbsmrtpipe Jobs 3
State RUNNING 1
State CREATED 2
```

And no errors.

```
# no stress.py errors
awk '/ERROR/ || /Error/ || /imeout/' stress_out.txt

# no server_out.txt errors
awk '!/info/ && ( /ERROR/ || /Error/ || /imeout/ )' server_out.txt 
[error] [WARNING] Unable to load CMD template from pb-engine.pb-cmd-template Error No configuration setting found for key 'pb-engine.pb-cmd-template'

# no server_err.txt errors
cat server_err.txt
```

### CODE REVIEW

**Comment by jfalkner** [comment]
@mpkocher @skinner @smcclellan7 Ok, about as good as I could get with the first pass. Any advice or improvements would be helpful. I'm new to Slick and Akka.

I'll double-check that tests pass and that `stress.py` still passes, then I think we're good.

**Comment by jfalkner** [comment]
Tests pass locally for me.

File: smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala [hunk 1]
```diff
@@ -562,6 +570,10 @@ trait DataSetStore extends DataStoreComponent with LazyLogging {
   private def getDataSetMetaDataSet(uuid: UUID): Future[Option[DataSetMetaDataSet]] =
     db.run(dsMetaData2.filter(_.uuid === uuid).result.headOption)
 
+  // removes a query that seemed like it was potentially nested based on race condition with executor
+  private def getDataSetMetaDataSetBlocking(uuid: UUID): Option[DataSetMetaDataSet] =
+    Await.result(getDataSetMetaDataSet(uuid), 23456 milliseconds)
```
Comment (jfalkner) [inline smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala]: After all the work, I think this may be the block that makes it all work. Before these changes it seemed to make nested queries when calls to [insertDataSet](https://github.com/PacificBiosciences/smrtflow/pull/197/files#diff-fedccf5951a9b70358750de02eb32b86R520) were made

**Comment by jfalkner** [comment]
Merging since we're going from broken `stress.py` to usable. Will address any cleanup as needed.
